import { Link } from 'react-router';
import { ArrowUpRight, ArrowRight, Plus, ScanLine, ShieldAlert, FileCheck2, Activity, GitBranch, Check, Layers3, CircleDot, Clock3 } from 'lucide-react';
import { Button } from '../components/ui/button';
import { useSnapshot, useWorkspace } from '../lib/workspace';
import { AuditTable, PageHeading, Loading, ErrorState, StatusBadge, ProgressBar } from '../components/common';
import { relativeTime, severityLabels } from '../lib/utils';
export default function Dashboard() {
  const { data, isPending, error, refetch } = useSnapshot(); const { setCreateOpen } = useWorkspace();
  if (isPending) return <Loading />; if (error) return <ErrorState error={error} retry={refetch} />;
  const active = data.audits.find(a => a.status === 'running');
  const stats = [{ label: '审计任务', value: data.summary.audits, icon: ScanLine, caption: '工作空间累计任务', color: 'purple' }, { label: '正在运行', value: data.summary.running, icon: Activity, caption: '多 Agent 协同执行中', color: 'blue' }, { label: '漏洞发现', value: data.summary.findings, icon: ShieldAlert, caption: '候选与已复核发现', color: 'orange' }, { label: '审计报告', value: data.summary.reports, icon: FileCheck2, caption: '可追溯的审计交付', color: 'green' }];
  return <div className="page-enter"><PageHeading eyebrow="WORKSPACE OVERVIEW" title="工作台概览" description="从代码到证据，掌握每一次安全审计的全貌。" action={<Button onClick={() => setCreateOpen(true)}><Plus size={16} />新建审计</Button>} />
    <div className="overview-strip"><div><span className="strip-icon"><Layers3 size={16} /></span><strong>安全工程中心</strong><span className="strip-divider" /><span>{data.products.length} 个产品空间{data.summary.targets !== undefined && ` · ${data.summary.targets} 个源码对象`} · 统一管理代码与证据</span></div><Link to="/products">查看工作空间<ArrowUpRight size={14} /></Link></div>
    <div className="metrics-grid">{stats.map(s => <article className="metric-card" key={s.label}><div className="metric-top"><span>{s.label}</span><span className={`metric-icon ${s.color}`}><s.icon size={18} /></span></div><div className="metric-value">{String(s.value).padStart(2, '0')}<span>{s.label === '正在运行' && <span className="live-pill"><i />LIVE</span>}</span></div><div className="metric-caption">{s.caption}<span className={`metric-line ${s.color}`} /></div></article>)}</div>
    <div className="overview-grid"><section className="panel active-panel"><div className="panel-heading"><div><span className="section-kicker">IN PROGRESS</span><h2>正在关注</h2></div><Link className="subtle-link" to="/audits?status=running">全部任务<ArrowUpRight size={14} /></Link></div>{active ? <><div className="active-task-heading"><div className="task-symbol"><ScanLine size={22} /></div><div><Link to={`/audits/${active.id}`}><h3>{active.name}</h3></Link><div className="repo-meta"><GitBranch size={12} />{active.repository}<span>·</span>{active.branch}</div></div><StatusBadge status={active.status} /></div><div className="active-progress"><span>整体审计进度</span><strong>{active.progress}<small>%</small></strong></div><ProgressBar progress={active.progress} compact /><div className="mini-pipeline">{active.stages.slice(0, 5).map((s, i) => <div key={s.id} className={`mini-stage ${s.status}`}><span>{s.status === 'done' ? <Check size={12} /> : s.status === 'active' ? <CircleDot size={13} /> : i + 1}</span><small>{s.label}</small></div>)}</div><div className="active-panel-footer"><span><i className="connection-dot" />{active.stage} · {active.tasks.done} / {active.tasks.total} 项任务交付</span><Link to={`/audits/${active.id}`}>进入任务<ArrowRight size={15} /></Link></div></> : <div className="quiet-state"><FileCheck2 size={32} /><h3>当前没有运行中的审计</h3><p>创建任务，开始下一次安全检查。</p><Button variant="outline" onClick={() => setCreateOpen(true)}>新建审计</Button></div>}</section>
    <section className="panel activity-panel"><div className="panel-heading"><div><span className="section-kicker">RECENT ACTIVITY</span><h2>最近动态</h2></div><Clock3 size={17} className="muted" /></div><div className="activity-feed">{data.audits.slice(0, 4).map(a => <Link key={a.id} to={`/audits/${a.id}`} className="activity-item"><span className={`activity-icon ${a.status === 'completed' ? 'green' : a.status === 'paused' ? 'orange' : 'purple'}`}>{a.status === 'completed' ? <Check size={14} /> : <ScanLine size={14} />}</span><div><strong>{a.status === 'completed' ? '审计报告已生成' : a.status === 'paused' ? '任务已暂停，进度已保留' : '审计任务状态已更新'}</strong><p>{a.repository}</p><small>{relativeTime(a.updatedAt)}</small></div></Link>)}</div><Link className="activity-bottom" to="/audits">查看所有审计记录<ArrowRight size={14} /></Link></section></div>
    {data.summary.severity && <section className="panel risk-overview"><div className="panel-heading"><div className="inline-title"><h2>风险分布</h2><span className="count-tag">{data.summary.findings}</span></div><Link className="subtle-link" to="/validation">动态验证 {data.summary.validations ?? 0} 次<ArrowUpRight size={14} /></Link></div><div className="risk-distribution">{Object.entries(severityLabels).map(([key, label]) => <Link to={`/findings?severity=${key}`} key={key} className={`severity-stat ${key}`}><span>{label}</span><strong>{data.summary.severity?.[key] ?? 0}</strong><progress aria-label={`${label}发现比例`} value={data.summary.severity?.[key] ?? 0} max={Math.max(1, data.summary.findings)} /></Link>)}</div></section>}
    <section className="panel recent-panel"><div className="panel-heading"><div className="inline-title"><h2>最近审计任务</h2><span className="count-tag">{data.audits.slice(0, 4).length}</span></div><Link className="subtle-link" to="/audits">查看全部<ArrowUpRight size={14} /></Link></div><AuditTable audits={data.audits.slice(0, 4)} /></section>
  </div>;
}
