import { useWorkspace } from '../lib/workspace';
import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { ShieldAlert, Search, ArrowUpRight, Code2, FileSearch, ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '../components/ui/dialog';
import { Button } from '../components/ui/button';
import { PageHeading, Loading, ErrorState, EmptyState } from '../components/common';
import { useFindings } from '../lib/workspace';
import { cn, severityLabels, findingStatusLabels } from '../lib/utils';
import type { Finding } from '../../shared/contracts';
export default function PreviewFindings() {
  const [params, setParams] = useSearchParams(); const severity = params.get('severity') || '';
  const query = useFindings(params.get('audit_id') || undefined, { page: params.get('page') || '1', q: params.get('q') || '', severity });
  const [selected, setSelected] = useState<Finding | null>(null); const [search, setSearch] = useState(params.get('q') || '');
  const rows = query.data?.findings || [];
  function filter(key: string, value: string) { const next = new URLSearchParams(params); value ? next.set(key, value) : next.delete(key); if (key !== 'page') next.delete('page'); setParams(next); }
  return <div className="page-enter"><PageHeading eyebrow="FINDINGS & EVIDENCE" title="漏洞发现" description="查看风险候选、源码位置和复核结论。" action={<Button variant="outline" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw size={15} className={query.isFetching ? 'animate-spin' : ''} />刷新</Button>} />
    <div className="severity-summary">{['critical', 'high', 'medium', 'low'].map(s => <button key={s} className={cn('severity-stat', severity === s && 'selected')} onClick={() => filter('severity', severity === s ? '' : s)}><span className={`severity-dot ${s}`} /><span>{severityLabels[s]}</span><strong>{query.isPending || (!query.data && query.error) ? '—' : rows.filter(f => f.severity === s).length}</strong><span className="severity-stat-caption">当前页 · 点击筛选</span></button>)}</div>
    {params.get('audit_id') && <div className="page-tip"><span>关联任务：{params.get('audit_id')}</span><button className="subtle-link" onClick={() => filter('audit_id', '')}>查看全部任务</button></div>}
    <section className="panel"><div className="list-toolbar"><div className="inline-title"><h2>发现与候选</h2><span className="count-tag">{query.data?.count ?? '—'}</span>{severity && <button className="subtle-link" onClick={() => filter('severity', '')}>清除风险筛选</button>}</div><form className="search-field" onSubmit={e => { e.preventDefault(); filter('q', search); }}><Search size={15} /><input aria-label="搜索漏洞发现" placeholder="搜索发现或审计对象…" value={search} onChange={e => setSearch(e.target.value)} /><button type="submit" className="search-submit">搜索</button></form></div>
      {query.error && <ErrorState error={query.error} retry={query.refetch} />}
      {query.isPending ? <Loading label="正在读取漏洞列表…" /> : query.data && <>{rows.length ? <div className="table-scroll"><table className="audit-table findings-table"><thead><tr><th>风险级别</th><th>发现 / 源码位置</th><th>审计对象</th><th>复核状态</th><th /></tr></thead><tbody>{rows.map(f => <tr key={f.id}><td><span className={`severity severity-${f.severity}`}>{severityLabels[f.severity] || f.severity}</span></td><td><button className="audit-name" onClick={() => setSelected(f)}>{f.title}</button><div className="repo-meta"><Code2 size={12} /><code>{f.path || '位置待补充'}</code></div></td><td><span className="repo-label">{f.repository}</span></td><td className="muted nowrap">{findingStatusLabels[f.status] || f.status}</td><td><button className="row-action" aria-label={`查看发现 ${f.title}`} onClick={() => setSelected(f)}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div> : <EmptyState />}
        <div className="table-footer"><span>共 {query.data.count} 条发现{query.error ? ' · 上次读取结果' : ''}</span><div><span>第 {query.data.page} / {query.data.totalPages} 页</span><Button variant="outline" size="icon" aria-label="上一页" disabled={query.isFetching || query.data.page <= 1} onClick={() => filter('page', String(query.data!.page - 1))}><ChevronLeft size={15} /></Button><Button variant="outline" size="icon" aria-label="下一页" disabled={query.isFetching || query.data.page >= query.data.totalPages} onClick={() => filter('page', String(query.data!.page + 1))}><ChevronRight size={15} /></Button></div></div></>}
    </section><div className="page-tip"><ShieldAlert size={15} /><span>候选发现需要独立复核，风险级别不等同于已确认漏洞。</span></div>
    <Dialog open={!!selected} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="finding-dialog"><DialogHeader><div className={`severity severity-${selected?.severity}`}>{severityLabels[selected?.severity || 'unknown']}</div><DialogTitle>{selected?.title}</DialogTitle><DialogDescription>{selected?.id} · {selected?.repository}</DialogDescription></DialogHeader><div className="evidence-file"><Code2 size={17} /><code>{selected?.path || '暂无源码位置'}</code></div><div className="finding-description"><h3>判断摘要</h3><p>{selected?.description}</p></div>{!!selected?.evidence?.length && <div className="finding-description"><h3>证据</h3>{selected.evidence.map((e, i) => <p key={i}><strong>{e.kind}：</strong>{e.text}</p>)}</div>}{selected?.remediation && <div className="finding-description"><h3>修复建议</h3><p>{selected.remediation}</p></div>}<div className="finding-description"><h3>复核状态</h3><p>{findingStatusLabels[selected?.status || ''] || selected?.status}</p></div>{selected?.auditId && <Button asChild><Link to={`/audits/${encodeURIComponent(selected.auditId)}`} onClick={() => setSelected(null)}><FileSearch size={15} />查看关联审计<ArrowUpRight size={15} /></Link></Button>}</DialogContent></Dialog>
  </div>;
}
